# Generated by Django 5.0.7 on 2024-10-14 11:17

import utils.jalalidate
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_key', models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('registerdate', utils.jalalidate.JalaliDateField(blank=True, null=True)),
                ('birthdate', utils.jalalidate.JalaliDateField(blank=True, null=True)),
                ('birthdatekey', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.postal_code_validator])),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('registration', models.BooleanField(blank=True, null=True)),
                ('address_validation', models.BooleanField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=64, null=True)),
                ('address', models.TextField(blank=True, max_length=64, null=True)),
                ('gendercode', models.IntegerField(blank=True, default=1, null=True, validators=[utils.validators.gender_validator])),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
            },
        ),
    ]
