# Generated by Django 5.0.7 on 2024-11-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='party_type_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
