# Generated by Django 5.0.7 on 2024-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_customer_type_code_customer_party_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organizationalcode',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
