# Generated by Django 5.0.7 on 2025-02-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_organizationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerCode',
            field=models.PositiveBigIntegerField(db_index=True, null=True, unique=True),
        ),
    ]
