# Generated by Django 5.0.7 on 2025-02-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_customercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_key',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
