# Generated by Django 5.0.7 on 2024-08-20 12:30

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postalcode', models.CharField(db_index=True, max_length=6, validators=[utils.validators.validate_length])),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True)),
                ('average_price', models.BigIntegerField(null=True)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Postal Map',
                'verbose_name_plural': 'Postal Maps',
                'db_table': 'postal_map',
                'ordering': ['postalcode'],
            },
        ),
        migrations.AddConstraint(
            model_name='postmap',
            constraint=models.UniqueConstraint(models.F('postalcode'), models.F('city'), models.F('neighborhood'), name='unique_row'),
        ),
    ]
