# Generated by Django 5.0.7 on 2024-08-20 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GnafBuildings',
            fields=[
                ('buildingid', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('parcel', models.JSONField(null=True)),
                ('geom', models.JSONField(null=True)),
                ('state_name', models.CharField(max_length=64)),
                ('locationtype', models.CharField(max_length=32)),
                ('locationname', models.CharField(max_length=128)),
                ('parish', models.CharField(max_length=256, null=True)),
                ('tour', models.CharField(max_length=5, null=True)),
            ],
            options={
                'db_table': 'gnaf_buildings',
            },
        ),
        migrations.CreateModel(
            name='GnafUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenue', models.TextField(null=True)),
                ('preaventypename', models.CharField(max_length=32, null=True)),
                ('preaven', models.TextField(null=True)),
                ('floorno', models.IntegerField(null=True)),
                ('tour', models.CharField(max_length=5, null=True)),
                ('plate_no', models.IntegerField()),
                ('unit', models.CharField(max_length=64, null=True)),
                ('activity', models.TextField(null=True)),
                ('postalcode', models.CharField(max_length=10)),
                ('address', models.TextField(null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='units', to='maskan.gnafbuildings')),
            ],
            options={
                'db_table': 'gnaf_units',
            },
        ),
        migrations.AddConstraint(
            model_name='gnafunits',
            constraint=models.UniqueConstraint(models.F('postalcode'), name='unique_postalcode'),
        ),
    ]
