# Generated by Django 5.0.7 on 2024-08-20 12:30

import utils.jalalidate
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maskan', '0002_gnafbuildings_gnafunits_gnafunits_unique_postalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmlakRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('trace_id_date', utils.jalalidate.JalaliDateField(null=True)),
                ('contract_code', models.CharField(blank=True, max_length=32, null=True)),
                ('estate_types_name', models.CharField(blank=True, max_length=64, null=True)),
                ('usage_types_name', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('price_rahn', models.BigIntegerField(blank=True, null=True)),
                ('price_monthly', models.BigIntegerField(blank=True, null=True)),
                ('price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('sale_sakht', models.IntegerField(blank=True, null=True)),
                ('frame_types_name', models.TextField(blank=True, null=True)),
                ('frontage_type_name', models.TextField(blank=True, null=True)),
                ('bedroom_count', models.IntegerField(blank=True, null=True)),
                ('unit_floor_side_name', models.CharField(blank=True, max_length=16, null=True)),
                ('tel_status_name', models.BooleanField(blank=True, null=True)),
                ('parking_status', models.BooleanField(blank=True, null=True)),
                ('elevator_status', models.BooleanField(blank=True, null=True)),
                ('warehouse_status', models.BooleanField(blank=True, null=True)),
                ('floors_count', models.IntegerField(blank=True, null=True)),
                ('floor_no', models.IntegerField(blank=True, null=True)),
                ('unit_per_floor', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amlak Rent',
                'verbose_name_plural': 'Amlaks Rent',
                'db_table': 'amlak_rents',
                'ordering': ['-trace_id_date'],
            },
        ),
        migrations.CreateModel(
            name='AmlakSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('trace_id_date', utils.jalalidate.JalaliDateField(null=True)),
                ('contract_code', models.CharField(blank=True, max_length=32, null=True)),
                ('estate_types_name', models.CharField(blank=True, max_length=64, null=True)),
                ('usage_types_name', models.TextField(blank=True, null=True)),
                ('area', models.FloatField(blank=True, null=True)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('sale_sakht', models.IntegerField(blank=True, null=True)),
                ('frame_types_name', models.TextField(blank=True, null=True)),
                ('frontage_type_name', models.TextField(blank=True, null=True)),
                ('unit_floor_side_name', models.CharField(blank=True, max_length=16, null=True)),
                ('tel_status_name', models.BooleanField(blank=True, null=True)),
                ('parking_status', models.BooleanField(blank=True, null=True)),
                ('elevator_status', models.BooleanField(blank=True, null=True)),
                ('warehouse_status', models.BooleanField(blank=True, null=True)),
                ('floors_count', models.IntegerField(blank=True, null=True)),
                ('floor_no', models.IntegerField(blank=True, null=True)),
                ('unit_per_floor', models.IntegerField(blank=True, null=True)),
                ('subscription_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Amlak Sale',
                'verbose_name_plural': 'Amlaks Sale',
                'db_table': 'amlak_sales',
                'ordering': ['-trace_id_date'],
            },
        ),
    ]
