# Generated by Django 5.0.7 on 2024-08-28 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('maskan', '0003_amlakrent_amlaksale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmap',
            name='average_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MaskanValueEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('mode_unit_per_floor', models.IntegerField(blank=True)),
                ('prediction_area', models.FloatField(blank=True, null=True)),
                ('prediction_area_price_per_m2', models.BigIntegerField(blank=True, null=True)),
                ('customer_key', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='maskan_estimation', to='customer.customer')),
            ],
            options={
                'db_table': 'unit_estimation',
            },
        ),
    ]
