# Generated by Django 5.0.7 on 2025-01-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_customer_organizationalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('totalDepositAmount', models.BigIntegerField()),
                ('averageDepositAmount', models.BigIntegerField()),
                ('totalWithdrawAmount', models.BigIntegerField()),
                ('averageWithdrawAmount', models.BigIntegerField()),
                ('maxCashFlowAmount', models.BigIntegerField()),
                ('minCashFlowAmount', models.BigIntegerField()),
                ('absoluteRevenue', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cashflow', to='customer.customer')),
            ],
            options={
                'verbose_name': 'cashflow',
                'verbose_name_plural': 'cashflowes',
                'db_table': 'cashflow_historical',
            },
        ),
        migrations.CreateModel(
            name='CashPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('weightedaverageCashAmount', models.BigIntegerField()),
                ('averageCashAmount', models.BigIntegerField()),
                ('maxCashAmount', models.BigIntegerField()),
                ('minCashAmount', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='CashPortfo', to='customer.customer')),
            ],
            options={
                'verbose_name': 'CashPortfo',
                'verbose_name_plural': 'CashPortfo',
                'db_table': 'CashPortfo_historical',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('credit_count', models.IntegerField()),
                ('averageCreditAmount', models.BigIntegerField()),
                ('maxCreditAmount', models.BigIntegerField()),
                ('minCreditAmount', models.BigIntegerField()),
                ('totalCreditAmount', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit', to='customer.customer')),
            ],
            options={
                'verbose_name': 'credit',
                'verbose_name_plural': 'credits',
                'db_table': 'credit_historical',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(db_index=True)),
                ('quarter', models.IntegerField(db_index=True)),
                ('countFundEbtal', models.IntegerField()),
                ('countFundSodur', models.IntegerField()),
                ('totalFundEbtalTradeAmount', models.BigIntegerField()),
                ('totalFundSodurTradeAmount', models.BigIntegerField()),
                ('averageallFundTradeAmount', models.BigIntegerField()),
                ('averageFundEbtalTradeAmount', models.BigIntegerField()),
                ('averageFundSodurTradeAmount', models.BigIntegerField()),
                ('maxFundTradeAmount', models.BigIntegerField()),
                ('minFundTradeAmount', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fund', to='customer.customer')),
            ],
            options={
                'verbose_name': 'fund',
                'verbose_name_plural': 'funds',
                'db_table': 'fund_historical',
            },
        ),
        migrations.CreateModel(
            name='Hami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('weightedaverageHamiquantity', models.BigIntegerField()),
                ('averageHamiquantity', models.BigIntegerField()),
                ('maxHamiquantity', models.BigIntegerField()),
                ('minHamiquantity', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hami', to='customer.customer')),
            ],
            options={
                'verbose_name': 'hami',
                'verbose_name_plural': 'hami',
                'db_table': 'hami_historical',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('countLogin', models.IntegerField()),
                ('distinctLoginweekDayNo', models.IntegerField()),
                ('distinctLoginmonthDayNo', models.IntegerField()),
                ('modeLoginmonthDayNo', models.IntegerField()),
                ('modeLoginweekDayNo', models.IntegerField()),
                ('averageLoginfrequency', models.IntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='login', to='customer.customer')),
            ],
            options={
                'verbose_name': 'login',
                'verbose_name_plural': 'logins',
                'db_table': 'login_historical',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('countOptiontrade', models.IntegerField()),
                ('countOptionstock', models.IntegerField()),
                ('totalOptiontradeAmount', models.BigIntegerField()),
                ('averageOptiontradeAmount', models.BigIntegerField()),
                ('maxOptiontradeAmount', models.BigIntegerField()),
                ('minOptiontradeAmount', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='option', to='customer.customer')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'option',
                'db_table': 'option_historical',
            },
        ),
        migrations.CreateModel(
            name='PortfolioValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('averagePortfolioValue', models.BigIntegerField()),
                ('maxPortfolioValue', models.BigIntegerField()),
                ('minPortfolioValue', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='portfoliovalue', to='customer.customer')),
            ],
            options={
                'verbose_name': 'portfoliovalue',
                'verbose_name_plural': 'portfoliovalues',
                'db_table': 'portfoliovalue_historical',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(db_index=True)),
                ('quarter', models.IntegerField(db_index=True)),
                ('countTradeStock', models.IntegerField()),
                ('countallTrade', models.IntegerField()),
                ('countBuyTrade', models.IntegerField()),
                ('countSellTrade', models.IntegerField()),
                ('totalTradeAmount', models.BigIntegerField()),
                ('totalBuyTradeAmount', models.BigIntegerField()),
                ('totalSellTradeAmount', models.BigIntegerField()),
                ('averageallTradeAmount', models.BigIntegerField()),
                ('averageBuyTradeAmount', models.BigIntegerField()),
                ('averageSellTradeAmount', models.BigIntegerField()),
                ('maxTradeAmount', models.BigIntegerField()),
                ('minTradeAmount', models.BigIntegerField()),
                ('customerKey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trade',
                'db_table': 'trade_historical',
            },
        ),
    ]
