# Generated by Django 5.0.7 on 2024-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(db_index=True, max_length=11, unique=True)),
                ('simtype', models.CharField(blank=True, max_length=128, null=True)),
                ('simoperator', models.CharField(blank=True, max_length=128, null=True)),
                ('simqualitytypeid', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sim Card',
                'verbose_name_plural': 'Sim Cards',
                'db_table': 'sim_card',
            },
        ),
    ]
