# Generated by Django 5.0.7 on 2024-08-28 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('simcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCardValueEstimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('sim_number', models.CharField(db_index=True, max_length=11)),
                ('estimated_price', models.BigIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='simcard_estimation', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Sim Card Value',
                'verbose_name_plural': 'Sim Cards Value',
                'db_table': 'sim_card_estimation',
            },
        ),
        migrations.AddConstraint(
            model_name='simcardvalueestimation',
            constraint=models.UniqueConstraint(models.F('customer'), models.F('sim_number'), name='unique_customer_sim'),
        ),
    ]
