# Generated by Django 5.0.7 on 2024-10-14 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('takhasos', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('jens', models.CharField(blank=True, max_length=4, null=True)),
                ('birthdatekey', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('nezam_pezeshki', models.CharField(blank=True, max_length=15, null=True)),
                ('customerkey', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to='customer.customer')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='GoldSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senf', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('customerkey', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='gold_seller', to='customer.customer')),
            ],
            options={
                'verbose_name': 'gold seller',
                'verbose_name_plural': 'gold sellers',
                'db_table': 'gold_seller',
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('officephone', models.CharField(blank=True, max_length=11, null=True)),
                ('status', models.CharField(default='active', max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('customerkey', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lawyer', to='customer.customer')),
            ],
            options={
                'verbose_name': 'lawyer',
                'verbose_name_plural': 'lawyers',
                'db_table': 'lawyers',
            },
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(models.F('name'), models.F('phone_number'), name='doctor_name_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='goldseller',
            constraint=models.UniqueConstraint(models.F('name'), models.F('phone_number'), name='goldseller_name_phone_number'),
        ),
        migrations.AddConstraint(
            model_name='lawyer',
            constraint=models.UniqueConstraint(models.F('name'), models.F('phone_number'), name='lawyer_name_phone_number'),
        ),
    ]
