# Generated by Django 5.0.7 on 2024-10-16 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('startdatekey', models.IntegerField(blank=True, null=True)),
                ('enddatekey', models.IntegerField(blank=True, null=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent', to='customer.customer')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
                'db_table': 'agents',
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(models.F('name'), models.F('phone_number'), models.F('customerkey'), name='agent_name_phone_number_customerkey'),
        ),
    ]
