# Generated by Django 5.0.7 on 2024-10-21 12:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_records', '0002_agent_agent_agent_name_phone_number_customerkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasmio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalcode', models.CharField(max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('is_valid_nationalcode', models.BooleanField(default=False)),
                ('is_male', models.BooleanField(blank=True, default=True, null=True)),
                ('companies_count', models.IntegerField(default=0)),
                ('company_id', models.CharField(blank=True, max_length=20, null=True)),
                ('company_title', models.CharField(blank=True, max_length=255, null=True)),
                ('position_title', models.CharField(blank=True, max_length=128, null=True)),
                ('first_role', models.CharField(blank=True, max_length=32, null=True)),
                ('second_role', models.CharField(blank=True, max_length=32, null=True)),
                ('representing_title', models.CharField(blank=True, max_length=128, null=True)),
                ('representing_id', models.CharField(blank=True, max_length=24, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('first_presence', models.DateField(blank=True, null=True)),
                ('void_date', models.DateField(blank=True, null=True)),
                ('by_latest_news', models.BooleanField(blank=True, default=False, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('void_by_news_id', models.CharField(blank=True, max_length=12, null=True)),
                ('by_news_id', models.CharField(blank=True, max_length=10, null=True)),
                ('all_roles', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), blank=True, null=True, size=None)),
                ('fetch_date', models.DateField(auto_now_add=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rasmio', to='customer.customer')),
            ],
            options={
                'verbose_name': 'rasmio',
                'verbose_name_plural': 'rasmio',
                'db_table': 'rasmio',
            },
        ),
    ]
