# Generated by Django 5.0.7 on 2024-11-04 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_records', '0003_rasmio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BamaCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, max_length=8, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('trim', models.CharField(blank=True, max_length=256, null=True)),
                ('gear_box', models.CharField(blank=True, max_length=16, null=True)),
                ('prod_year', models.IntegerField(blank=True, null=True)),
                ('usage_km', models.IntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=32, null=True)),
                ('body_status', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('authenticated', models.BooleanField(blank=True, null=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bama', to='customer.customer')),
            ],
            options={
                'verbose_name': 'bama',
                'verbose_name_plural': 'bama',
                'db_table': 'bama',
            },
        ),
    ]
