# Generated by Django 5.0.7 on 2024-11-23 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('customer_records', '0006_sheypoorhomerent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheypoorHomeSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.CharField(blank=True, max_length=16, null=True)),
                ('price', models.CharField(blank=True, max_length=16, null=True)),
                ('price_sqrm', models.CharField(blank=True, max_length=16, null=True)),
                ('ad_type', models.CharField(blank=True, max_length=16, null=True)),
                ('room', models.CharField(blank=True, max_length=16, null=True)),
                ('parking', models.CharField(blank=True, max_length=8, null=True)),
                ('storage', models.CharField(blank=True, max_length=8, null=True)),
                ('elevator', models.CharField(blank=True, max_length=8, null=True)),
                ('age', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=128, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=16, null=True)),
                ('seller_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('full_attr', models.CharField(blank=True, max_length=2048, null=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sheypoor_homesale', to='customer.customer')),
            ],
            options={
                'verbose_name': 'sheypoor_homesale',
                'verbose_name_plural': 'sheypoor_homesale',
                'db_table': 'sheypoor_homesale',
            },
        ),
        migrations.CreateModel(
            name='SheypoorVillaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=32, null=True)),
                ('area', models.CharField(blank=True, max_length=32, null=True)),
                ('price', models.CharField(blank=True, max_length=16, null=True)),
                ('price_sqrm', models.CharField(blank=True, max_length=16, null=True)),
                ('room', models.CharField(blank=True, max_length=16, null=True)),
                ('parking', models.CharField(blank=True, max_length=8, null=True)),
                ('storage', models.CharField(blank=True, max_length=8, null=True)),
                ('balcony', models.CharField(blank=True, max_length=8, null=True)),
                ('age', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=64, null=True)),
                ('reg_date', models.CharField(blank=True, max_length=16, null=True)),
                ('seller_profile', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('full_attr', models.CharField(blank=True, max_length=2048, null=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sheypoor_villasale', to='customer.customer')),
            ],
            options={
                'verbose_name': 'sheypoor_villasale',
                'verbose_name_plural': 'sheypoor_villasale',
                'db_table': 'sheypoor_villasale',
            },
        ),
    ]
