# Generated by Django 5.0.7 on 2024-12-14 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_organizationalcode'),
        ('customer_records', '0007_sheypoorhomesale_sheypoorvillasale'),
    ]

    operations = [
        migrations.CreateModel(
            name='PazirehNevisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuerkey', models.IntegerField()),
                ('issuerSymbol', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('customerkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pazireh', to='customer.customer')),
            ],
            options={
                'verbose_name': 'pazireh_neveisi',
                'verbose_name_plural': 'pazireh_neveisi',
                'db_table': 'pazireh_neveisi',
            },
        ),
    ]
