# Generated by Django 5.0.7 on 2024-12-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_organizationalcode'),
        ('customer_records', '0008_pazirehnevisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArzeAvvalieh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuerkey', models.IntegerField()),
                ('stockKey', models.IntegerField()),
                ('issuerSymbol', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitPrice', models.BigIntegerField(blank=True, null=True)),
                ('firstTradeDateKey', models.IntegerField(blank=True, null=True)),
                ('customerkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arze_avvalieh', to='customer.customer')),
            ],
            options={
                'verbose_name': 'arze_avvalieh',
                'verbose_name_plural': 'arze_avvalieh',
                'db_table': 'arze_avvalieh',
            },
        ),
    ]
