# Generated by Django 5.0.7 on 2025-03-04 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_customer_key'),
        ('customer_records', '0009_arzeavvalieh'),
    ]

    operations = [
        migrations.CreateModel(
            name='YadDasht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(blank=True, max_length=32, null=True)),
                ('comment', models.CharField(blank=True, max_length=512, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('customerkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='yaddasht', to='customer.customer')),
            ],
            options={
                'verbose_name': 'yaddasht',
                'verbose_name_plural': 'yaddasht',
                'db_table': 'yaddasht',
            },
        ),
    ]
