# Generated by Django 5.0.7 on 2025-04-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_customer_key'),
        ('customer_records', '0010_yaddasht'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(max_length=500, null=True)),
                ('company_type_id', models.IntegerField(null=True)),
                ('company_type_description', models.CharField(max_length=500)),
                ('state_id', models.IntegerField(null=True)),
                ('state_description', models.CharField(max_length=500)),
                ('company_national_code', models.CharField(max_length=50)),
                ('register_number', models.CharField(max_length=50, null=True)),
                ('economic_code', models.CharField(max_length=50, null=True)),
                ('bourse_symbol', models.CharField(max_length=250, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('post_code', models.CharField(max_length=50, null=True)),
                ('address_desc', models.TextField(null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('email_address', models.EmailField(max_length=255, null=True)),
                ('parent_count', models.IntegerField(null=True)),
                ('child_count', models.IntegerField(null=True)),
                ('count_portfo', models.IntegerField(null=True)),
                ('gazette_stock', models.FloatField(null=True)),
                ('last_change', models.JSONField(null=True)),
                ('customerkey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linka', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Linka',
                'verbose_name_plural': 'Linka',
                'db_table': 'linka',
            },
        ),
    ]
